version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: .next
  name: .next

  secondary-artifacts:
    static_assets:
      files:
        - "**/*"
      base-directory: src/static-assets
