version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - dist/**/*
    - package.json
